services:
  orders:
    build:
      context: ./orders
    environment:
      HOST: db
      USERNAME: user
      PASSWORD: password
      DATABASE: common

  products:
    build:
      context: ./products
    environment:
      HOST: db
      USERNAME: user
      PASSWORD: password
      DATABASE: common

  users:
    build:
      context: ./user
    environment:
      HOST: db
      USERNAME: user
      PASSWORD: password
      DATABASE: common

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: common
    volumes:
      - db_data:/var/lib/postgresql/data

  reverse_proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:3000"
      - "4000:4000"
      - "5000:5000"

volumes:
  db_data: